<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_State  Province  Region</name>
   <tag></tag>
   <elementGuidId>8a843442-519f-460b-9753-b6d7ee2bd8d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formCover']/div[3]/div[2]/sec-view[2]/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0b2471a9-f8aa-4052-949d-83f111879a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>labelClicked()</value>
      <webElementGuid>d30a5040-1cf0-4ec1-835a-b10ebbc2967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-mouseout</name>
      <type>Main</type>
      <value>labelOut()</value>
      <webElementGuid>c1ac03f2-aa7a-4010-a7a1-11c986876cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>State / Province / Region</value>
      <webElementGuid>99b7a0f6-7889-4204-b588-2db50391de93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formCover&quot;)/div[3]/div[@class=&quot;spliter&quot;]/sec-view[@class=&quot;ng-isolate-scope sec-view&quot;]/div[@class=&quot;inputContainer ng-scope&quot;]/label[1]</value>
      <webElementGuid>669a3837-c84c-4a40-8b25-f8684a564097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formCover']/div[3]/div[2]/sec-view[2]/div/label</value>
      <webElementGuid>74e7a5a9-b27e-43d2-88cf-72fab7b41d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/sec-view[2]/div/label</value>
      <webElementGuid>5dea5891-54dd-40af-a752-71272448a52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'State / Province / Region' or . = 'State / Province / Region')]</value>
      <webElementGuid>8fd312aa-1ebc-4ad1-b5bf-dde8fd0a0b52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
