<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit shipping details</name>
   <tag></tag>
   <elementGuidId>6c23604c-b711-42ef-bacd-75bc25a5e8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.blueLink > a.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userSection']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3d931a5-faa4-446d-ba4b-095438b7dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>3e54e94a-7bf4-44ea-93ef-85eeba135333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setUserDetailsEditMode()</value>
      <webElementGuid>4ae139f3-6339-4655-b423-e736c62c2db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit_shipping_Details</value>
      <webElementGuid>b426dd34-6c90-4c42-9df2-ee4b4c2467b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>072ba353-603d-4b4d-ab16-69c3c192c562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>c1120884-fea8-49b8-bf1e-89cb6f715418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit shipping details</value>
      <webElementGuid>138a8bcf-28e9-497e-82df-02840e40c4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;blueLink&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>6a1faebb-bdc1-43e1-a4a4-dbaff78f0e91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[2]/a</value>
      <webElementGuid>e3b6a704-455c-43da-bed7-32329b56dcd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit shipping details')]</value>
      <webElementGuid>bf0c7402-6b3f-486b-b4eb-b936dd5823df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>3926bdb4-fb98-4194-ac98-e904025f1912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>06453164-615d-4a42-adf8-dd7a5b2ae1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Edit shipping details' or . = 'Edit shipping details')]</value>
      <webElementGuid>dbba0fc5-9223-465e-ae47-7185874a7da8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
