<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>0960856f-4f3a-421a-b606-79d02ea3e706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav.pages.fixedImportant.productImage.ng-scope > a.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'HOME')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c957e48c-abf4-48f1-ab44-e9334bd54dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>df5df13c-798e-4ad1-8ffb-41a1ac014603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/#</value>
      <webElementGuid>85beaa84-022e-495e-87eb-f0f67c94f334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>68e3c799-541d-4c4d-955d-bec4ebcd9117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>50c33072-e4d4-4043-be8d-83b72b690900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;uiview ng-scope&quot;]/nav[@class=&quot;pages fixedImportant productImage ng-scope&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>fceaa4d7-beb3-48f1-b473-de980ff4afbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>d9368c5f-e057-4628-9b8b-897c4244c477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/#')]</value>
      <webElementGuid>81c795a7-9d81-4473-80e6-2c3f44b88072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>eacd7fcc-67da-4a5b-b5eb-871f20c3dd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/#' and (text() = 'HOME' or . = 'HOME')]</value>
      <webElementGuid>844a01c9-d6cf-4d2c-8feb-282a33f0138c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
