<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAY NOW_1</name>
   <tag></tag>
   <elementGuidId>1ce53164-8b26-46d8-8ec7-441f38121ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pay_now_btn_ManualPayment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pay_now_btn_ManualPayment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67f6580b-5e93-4751-be45-b559b7cd313f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pay_now_btn_ManualPayment</value>
      <webElementGuid>7156153b-a98c-4ae4-a353-f6600e2c188b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ac36c66-47da-4289-a47a-f980fa4007dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sec-sender-a ng-scope</value>
      <webElementGuid>2f9c4cc9-6634-40ae-a03c-f64289f5c6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3800c38f-ce89-4a9d-9a50-c5669f72d372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>senderCtrl.send()</value>
      <webElementGuid>2504e2a7-7cc7-43b0-b19e-e600501c7e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAY NOW</value>
      <webElementGuid>b7c86f09-b4bc-481a-b5a3-27dfc38d5273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pay_now_btn_ManualPayment&quot;)</value>
      <webElementGuid>c7da6de2-a980-4d0a-a7e4-1cc5177f25f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pay_now_btn_ManualPayment']</value>
      <webElementGuid>ad3cd839-fe89-4123-a0b6-dc6ecd2aeeeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div[4]/label/sec-sender/button</value>
      <webElementGuid>7a1aa1a4-8da0-4b50-94b4-cad85b9f1bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label/sec-sender/button</value>
      <webElementGuid>4f4116b2-e071-4e5e-8d92-785c2838e95a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pay_now_btn_ManualPayment' and @type = 'button' and (text() = 'PAY NOW' or . = 'PAY NOW')]</value>
      <webElementGuid>ae01d410-f0ef-460f-9794-9036b4ef975b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
