<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img17</name>
   <tag></tag>
   <elementGuidId>51722675-592a-4df9-afb2-51723f0770c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#17</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='17']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7ee91f1b-b96b-40be-ab6b-6128836f004e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>3440237a-404d-48fb-a856-659aa6bc9831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>cbf21431-c5c4-4a8b-ac40-57bb38c7ae7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>610a45fa-78e9-4d5b-9bd7-9313a2098090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3200</value>
      <webElementGuid>8ea656c1-fbb0-4759-a67d-6c163d5833b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3200</value>
      <webElementGuid>a8a6186c-764f-42d8-9ff6-7f822cd80af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17&quot;)</value>
      <webElementGuid>43eba865-96bd-4def-8413-863c05c89a90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='17']</value>
      <webElementGuid>3eae490b-f542-4d6b-a4cf-7b1116db4506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>8ad26c64-aaa5-417f-af4b-a29ff5a5a15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '17' and @src = '/catalog/fetchImage?image_id=3200']</value>
      <webElementGuid>894ed6b0-20d7-49d3-858f-7404905add9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
