<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_card_number</name>
   <tag></tag>
   <elementGuidId>8905943f-c7d9-42c2-af1d-b1506373aa18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#creditCard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='creditCard']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11064cc2-56be-4c6f-87df-919b9c6c034c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>creditCard</value>
      <webElementGuid>678be8d2-b301-49f8-a385-9e6d1a0549d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>2471f9f8-2e1d-4577-9aeb-3479bda9f902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>secModel</value>
      <webElementGuid>8fc744d8-6f11-4b74-9ddb-cb68dc0b50f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>2a0427a8-983b-476d-b8f3-48a58bacab46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid ng-scope ng-valid-maxlength in-focus card-number-four-digits ng-dirty-add ng-valid-parse-add ng-animate ng-pristine-remove</value>
      <webElementGuid>be82d952-f8b0-45f4-bcdc-cc59fcbfadb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-animate</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a84ace36-b088-4b1a-bb6f-87ffe7fb1ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;creditCard&quot;)</value>
      <webElementGuid>8e4a0327-02bf-4de1-9178-0e6b3029b6ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='creditCard']</value>
      <webElementGuid>3d6c73c3-0942-4f5c-8704-e65302f5a058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>4179d189-a592-4e7e-ac52-b0a75c0c4223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/sec-form/div/sec-view/div/input</value>
      <webElementGuid>3e9e49b7-91ec-43b2-a4b5-e0b4326210e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'creditCard' and @name = 'card_number']</value>
      <webElementGuid>b6945bbf-c378-48d5-a800-b0e47b153dcc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
