<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Shop Now</name>
   <tag></tag>
   <elementGuidId>7c3cb1a8-435b-4216-a7aa-c04e7ab23356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabletsLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='tabletsLink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4e025d66-ad98-43dc-b074-5bfde2e14ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabletsLink</value>
      <webElementGuid>eec349cd-b662-4e08-b4b3-bb6785a995ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub roboto-regular ng-scope</value>
      <webElementGuid>0f50f785-8a59-4e7d-9411-d90cbdb560bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Shop_Now</value>
      <webElementGuid>f84bdbb4-0b8c-4773-92cb-3d84a6bd4db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop Now</value>
      <webElementGuid>7740cdda-5624-4ec3-b5fe-020afed7b8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabletsLink&quot;)</value>
      <webElementGuid>706e0466-174b-4536-8198-bcc36529eccc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='tabletsLink']</value>
      <webElementGuid>ea1f201a-8d65-4c8f-92c2-c7b5bf51985c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabletsImg']/div/label</value>
      <webElementGuid>785f8878-1d44-45ec-bde0-d5de80b81f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>f4389418-e71a-481a-a7e2-cf03f2fcd5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'tabletsLink' and (text() = 'Shop Now' or . = 'Shop Now')]</value>
      <webElementGuid>471bfa01-8506-450a-8cc9-c7d4e280d9b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
