<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img2</name>
   <tag></tag>
   <elementGuidId>99483e10-dd77-4d46-94fa-491365f71dfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>791dad2a-4924-447f-a5ba-9ac3a71043b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>dbb8fd48-17e6-4248-9c3f-fc67f1da6941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>d154c7aa-c2e6-4a00-a012-a0ed67f605e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>acfd1759-07ef-4582-bcda-e345d771d0f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=1200</value>
      <webElementGuid>5f3890f6-875e-4dd7-8fc5-b555430983c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=1200</value>
      <webElementGuid>951b361d-d27c-4077-ae3a-f1a5d18f5bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2&quot;)</value>
      <webElementGuid>fe2983d0-6152-48fd-b1ce-eb92f2f8a7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='2']</value>
      <webElementGuid>b962941f-5f6b-4fa7-a901-44b7e4d88850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/img</value>
      <webElementGuid>014ec967-1ddf-4076-9af7-7d700032e37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '2' and @src = '/catalog/fetchImage?image_id=1200']</value>
      <webElementGuid>8ae22bfa-f509-45fc-bf3a-86ee0b9d40e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
