<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_operating_system_1</name>
   <tag></tag>
   <elementGuidId>ae1563bc-66c1-492c-b044-4f6bd0005cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operating_system_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operating_system_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>028c8ab2-fde1-4424-a237-cd253f460c07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_system_1</value>
      <webElementGuid>d21ddedd-d47f-4ba5-9b87-b17911d1e108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f6db3a7b-f95a-4455-971e-d34031b52894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>1f55259a-d3a9-4402-b580-6df5796e159d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>fa187f01-cefb-4aca-b270-8a3a16c079aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operating_system_1</value>
      <webElementGuid>415d8839-9e8c-4376-9389-8bfc15a427aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>8ab3e102-6b83-4a63-bb89-7ed490670369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operating_system_1&quot;)</value>
      <webElementGuid>6000c0e7-f46e-4dde-8055-a086cef70ff3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operating_system_1']</value>
      <webElementGuid>3db8fe9d-afd5-48b4-93f1-6a749b856920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div[2]/div/input</value>
      <webElementGuid>9e829686-bb27-47ca-8c4e-ac141593bc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[2]/div/input</value>
      <webElementGuid>e1102844-70c3-4b01-9ba9-579d3f3c2ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'operating_system_1' and @type = 'checkbox' and @id = 'operating_system_1']</value>
      <webElementGuid>ef02ec6e-308c-4186-909c-d54dc164ee15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
