<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_operating_system_0</name>
   <tag></tag>
   <elementGuidId>b0d2d0c9-b7ac-4122-ad38-4038817e9537</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operating_system_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operating_system_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27a34b6d-ad8e-4fa4-83f1-6bd9f5b1db32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_system_0</value>
      <webElementGuid>d4c35359-c90a-455c-aba9-8bec218c49d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>15150ffd-1805-4282-b4c2-6d9adf4df616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>cf9b30dd-c33d-4f1e-9b3d-9c76a0c5242d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>a9413e79-5fd7-4780-8dca-014222cd8436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operating_system_0</value>
      <webElementGuid>b31be49c-3969-4501-a228-3017ab94efe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>6e2028d1-8a14-4bfe-9729-6dcf1f60efd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operating_system_0&quot;)</value>
      <webElementGuid>50895531-9d88-4d1b-88fd-41d035972c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operating_system_0']</value>
      <webElementGuid>6057da2f-56f1-42cb-8789-03a6b778a42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div/div/input</value>
      <webElementGuid>c05fe663-33e4-4c95-9b4f-54aab825d671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div/div/input</value>
      <webElementGuid>4374dc99-f850-4a30-b9a3-866e4873b1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'operating_system_0' and @type = 'checkbox' and @id = 'operating_system_0']</value>
      <webElementGuid>5ab4c5b2-77fa-4e2f-8134-adfe0e502794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
