<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_operating_system_3</name>
   <tag></tag>
   <elementGuidId>636d0677-c456-47e6-b89f-8ea4e389f60e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operating_system_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operating_system_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eda5aab-6192-48bd-ac8f-51fd10c8ce05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_system_3</value>
      <webElementGuid>97827d29-383f-4439-881c-12c67a1ec9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c5b83358-9b24-4bcb-8009-683cb8d01dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>bd9f6b56-4500-449c-98c4-5208e729dbd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>330bed54-f610-4dcc-8eec-c57fa918c25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operating_system_3</value>
      <webElementGuid>d22ad3b7-21d7-49db-91c0-dec5f47f8646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>8b8eefa3-7c7d-45d7-bf48-fc0fd6791a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operating_system_3&quot;)</value>
      <webElementGuid>72a41875-8f77-4131-9291-8f128b6d209f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operating_system_3']</value>
      <webElementGuid>f0298009-93cc-4b20-94e1-c483ea7a7a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div[4]/div/input</value>
      <webElementGuid>e2092ba6-bc0d-4a84-8723-c196e5605c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[4]/div/input</value>
      <webElementGuid>d3ac7fc4-af35-4a47-98fd-2c96c84e18a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'operating_system_3' and @type = 'checkbox' and @id = 'operating_system_3']</value>
      <webElementGuid>14539ce2-e27d-4c2d-b878-f2761150f5f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
