<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_operating_system_2</name>
   <tag></tag>
   <elementGuidId>d17c0a9f-9e33-48a6-ab5c-7b6fb9f0daba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#operating_system_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='operating_system_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c79f74a0-b8cb-4dd4-aa0a-97473de2b86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>operating_system_2</value>
      <webElementGuid>25918d0e-9db7-49d4-94f7-f9b13dbb264e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e663b9a8-9fd3-4e83-8388-2496573a64bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>e6a7973b-6e3e-4011-b841-92530d99ea68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>c37db946-6d4c-4805-8bbe-4e8bc3b86e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>operating_system_2</value>
      <webElementGuid>b29dd3db-9461-4ded-914c-13c4efef2133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>432f0ba8-20ae-425f-a233-3df02812bbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;operating_system_2&quot;)</value>
      <webElementGuid>07dce327-bddc-48be-b6ff-ed10eb2f931f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='operating_system_2']</value>
      <webElementGuid>ee170185-f81d-418b-9b67-2b879718bd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/div/div[3]/div/input</value>
      <webElementGuid>91ee73a4-ac2e-4398-a419-0c8a0ad57e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div/div[3]/div/input</value>
      <webElementGuid>20c5a38c-b5de-422e-b58f-cdb65d7249ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'operating_system_2' and @type = 'checkbox' and @id = 'operating_system_2']</value>
      <webElementGuid>e2e2e16b-606d-4814-89f8-fb3242e6ae70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
