<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT (2,558.00)</name>
   <tag></tag>
   <elementGuidId>4c005d75-92c6-4ddc-ae58-cb8e33090043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkOutButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bae178b-dc0c-4d70-b3f4-62723a2e76f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bca64607-3afd-46b6-9250-ab3cf6fdfa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium tami uft-class ng-binding</value>
      <webElementGuid>359df6d0-5b43-4061-a8af-310837368c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout()</value>
      <webElementGuid>7268d296-7427-48d1-999d-d955337e542b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutButton</value>
      <webElementGuid>eef01115-7b19-460c-9e43-09a390e9b7a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>1fcafcc1-1710-45c3-af05-db46f522944e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT ($2,558.00)</value>
      <webElementGuid>6dd58aed-0e64-4226-9d50-cb1a8a11c82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutButton&quot;)</value>
      <webElementGuid>f8df4231-4dac-406a-99a9-3bf4514ccfa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutButton']</value>
      <webElementGuid>5fb800a1-3ec1-4101-9222-58b30d7872d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>ce5fdb4a-2a04-409e-8c8a-30744092fa2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>d5b8d9ad-188a-46b5-8f31-97c316c512a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutButton' and @name = 'check_out_btn' and (text() = 'CHECKOUT ($2,558.00)' or . = 'CHECKOUT ($2,558.00)')]</value>
      <webElementGuid>f931718e-8d6e-40e4-bef5-558b69941047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
