<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_masterCredit</name>
   <tag></tag>
   <elementGuidId>590b3ea6-431c-4e44-be9f-ca14fdb88a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;masterCredit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='masterCredit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f9559ab-d4d8-41da-852d-56c546c6ad65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>16441f87-c81e-4551-be13-51c2c6ac4def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>masterCredit</value>
      <webElementGuid>ecca5af0-c1cd-463f-a3fb-bdd2d81eeebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-checked</name>
      <type>Main</type>
      <value>checkedRadio == 2</value>
      <webElementGuid>18be9ffc-0b30-4d9b-b81f-2456afb79dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[@class=&quot;paymentMethods&quot;]/div[@class=&quot;imgRadioButton&quot;]/input[1]</value>
      <webElementGuid>ec137f46-b7a3-4705-9996-00c20a8302f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='masterCredit']</value>
      <webElementGuid>7a7aeaa5-fef2-447c-a73c-071b44dc5c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div/div[2]/input</value>
      <webElementGuid>cd149159-c9e0-4abd-8679-2377e6d65b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>30f81b62-fd0e-47fc-9b58-f5f5076938db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'masterCredit']</value>
      <webElementGuid>2c647a9b-9d51-48e1-959f-a68ca98a50b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
