<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Edit</name>
   <tag></tag>
   <elementGuidId>8717f446-cf13-4370-a6c8-c01f4641f409</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.edit.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='paymentMethod']/div/div[3]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f770c5ae-8d18-4398-9c82-798195cdc4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit  ng-scope</value>
      <webElementGuid>05134c94-bcbe-464e-992a-fa5175b2eee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>toggleShowMasterCart()</value>
      <webElementGuid>da2dddc5-19ee-40e5-b00e-d16cd7e53296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>d48bb6a8-0bda-40bb-b6b8-fe18c35ee1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>b462d920-9281-4a4b-8d7c-17879da26af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethod&quot;)/div[1]/div[3]/div[@class=&quot;masterCreditSeccion&quot;]/div[@class=&quot;roboto-regular&quot;]/label[@class=&quot;edit  ng-scope&quot;]</value>
      <webElementGuid>e5e9861b-771f-47fc-96ec-ab1baac70a44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethod']/div/div[3]/div/div/label</value>
      <webElementGuid>9d93fa03-2ff7-4720-b0ad-fa82772ecd5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div/div/label</value>
      <webElementGuid>b08b6e01-8680-435b-ae1b-d147cee09c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>52cd12b4-93d7-4a70-8a36-a875830dcba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
