<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Management Console_menuCart</name>
   <tag></tag>
   <elementGuidId>28c518b1-b58d-4cb0-86c6-43140217c82c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuCart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//svg[@id = 'menuCart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8ecdf2b0-ebc3-463b-9bff-be4de24a9a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuCart</value>
      <webElementGuid>6a406d95-1044-4edd-9934-2e96005bf3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>d0ebe15c-fb6f-4ab5-99a2-220b9874dd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b1fcf886-8daa-4502-af3c-7e2542d29b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>8b994ef8-cd23-46c1-8dc9-6dd97a0a1ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>044d7a48-987b-42ea-9956-cc4949a55fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>13134e64-8870-4af1-a1a9-561aa50849fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>9d1d1fa6-aecd-44bd-9b57-357a25b21640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>2bac700b-d865-416e-90f0-d1514106554e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>119a53dc-8a16-47bf-b54e-7bddf04b01c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enable-background</name>
      <type>Main</type>
      <value>new 0 0 24 24</value>
      <webElementGuid>97e33354-51c9-4037-b7db-324555aee265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xml:space</name>
      <type>Main</type>
      <value>preserve</value>
      <webElementGuid>537da3e7-382e-46aa-8ba2-f1ca36575cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuCart&quot;)</value>
      <webElementGuid>560eb01c-a666-4efa-8469-2d42eba8f2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'menuCart']</value>
      <webElementGuid>eb958437-ca8d-407c-8cb5-b7a541679711</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
